### PR TITLE
add install libuv for Kestrel

### PR DESCRIPTION
**Pull request by krabishe**

### CODE REVIEW

**Comment by juliankay** [comment]
Isn't this handled by [a nuget package](https://github.com/aspnet/libuv-package) now? Or have you had issues with that?

**Comment by krabishe** [comment]
Yes, I've got follow exception:

```
api_1  | Unhandled Exception:
api_1  | System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: libuv
api_1  |   at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods:uv_loop_size ()
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size () <0x408b62a0 + 0x0001c> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv uv) <0x408b6210 + 0x00037> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x408b5cb0 + 0x000ff> in <filename unknown>:0
api_1  |   --- End of inner exception stack trace ---
api_1  |   at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) <0x408d6bd0 + 0x0003f> in <filename unknown>:0
api_1  |   at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) <0x408b6310 + 0x000cf> in <filename unknown>:0
api_1  |   at System.Threading.Tasks.Task.Wait () <0x408b62d0 + 0x0002b> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.Start (Int32 count) <0x408ab680 + 0x000ab> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext] (IHttpApplication`1 application) <0x4089c3b0 + 0x0059f> in <filename unknown>:0
api_1  | ---> (Inner Exception #0) System.DllNotFoundException: libuv
api_1  |   at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods:uv_loop_size ()
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size () <0x408b62a0 + 0x0001c> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv uv) <0x408b6210 + 0x00037> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x408b5cb0 + 0x000ff> in <filename unknown>:0 <---
api_1  | [ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: libuv
api_1  |   at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods:uv_loop_size ()
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size () <0x408b62a0 + 0x0001c> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv uv) <0x408b6210 + 0x00037> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x408b5cb0 + 0x000ff> in <filename unknown>:0
api_1  |   --- End of inner exception stack trace ---
api_1  |   at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) <0x408d6bd0 + 0x0003f> in <filename unknown>:0
api_1  |   at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) <0x408b6310 + 0x000cf> in <filename unknown>:0
api_1  |   at System.Threading.Tasks.Task.Wait () <0x408b62d0 + 0x0002b> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.Start (Int32 count) <0x408ab680 + 0x000ab> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext] (IHttpApplication`1 application) <0x4089c3b0 + 0x0059f> in <filename unknown>:0
api_1  | ---> (Inner Exception #0) System.DllNotFoundException: libuv
api_1  |   at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods:uv_loop_size ()
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size () <0x408b62a0 + 0x0001c> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv uv) <0x408b6210 + 0x00037> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x408b5cb0 + 0x000ff> in <filename unknown>:0 <---
api_1  | Unhandled Exception:
api_1  | System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: libuv
api_1  |   at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods:uv_loop_size ()
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size () <0x408b62a0 + 0x0001c> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv uv) <0x408b6210 + 0x00037> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x408b5cb0 + 0x000ff> in <filename unknown>:0
api_1  |   --- End of inner exception stack trace ---
api_1  |   at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) <0x408d6bd0 + 0x0003f> in <filename unknown>:0
api_1  |   at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) <0x408b6310 + 0x000cf> in <filename unknown>:0
api_1  |   at System.Threading.Tasks.Task.Wait () <0x408b62d0 + 0x0002b> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.Start (Int32 count) <0x408ab680 + 0x000ab> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext] (IHttpApplication`1 application) <0x4089c3b0 + 0x0059f> in <filename unknown>:0
api_1  | ---> (Inner Exception #0) System.DllNotFoundException: libuv
api_1  |   at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods:uv_loop_size ()
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size () <0x408b62a0 + 0x0001c> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv uv) <0x408b6210 + 0x00037> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x408b5cb0 + 0x000ff> in <filename unknown>:0 <---
api_1  | [ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: libuv
api_1  |   at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods:uv_loop_size ()
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size () <0x408b62a0 + 0x0001c> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv uv) <0x408b6210 + 0x00037> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x408b5cb0 + 0x000ff> in <filename unknown>:0
api_1  |   --- End of inner exception stack trace ---
api_1  |   at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) <0x408d6bd0 + 0x0003f> in <filename unknown>:0
api_1  |   at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) <0x408b6310 + 0x000cf> in <filename unknown>:0
api_1  |   at System.Threading.Tasks.Task.Wait () <0x408b62d0 + 0x0002b> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.Start (Int32 count) <0x408ab680 + 0x000ab> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext] (IHttpApplication`1 application) <0x4089c3b0 + 0x0059f> in <filename unknown>:0
api_1  | ---> (Inner Exception #0) System.DllNotFoundException: libuv
api_1  |   at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods:uv_loop_size ()
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.loop_size () <0x408b62a0 + 0x0001c> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv uv) <0x408b6210 + 0x00037> in <filename unknown>:0
api_1  |   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x408b5cb0 + 0x000ff> in <filename unknown>:0 <---
```

**Comment by juliankay** [comment]
I'll take a look and see if I can replicate the issue first.

Is this the optimal version of libuv? Looks like it is from February 2015.

Also the comment doesn't correctly reflect the version of Ubuntu, so I'd like that to be modified.

**Comment by iamthemovie** [comment]
Closing this PR as it is out of date and we have upgraded to Preview 2. If the problem still persists then we will cross that bridge when we come to it.

**Pull request closed without merging**
